config/routes.rb
TimelineKeeper::Engine.routes.draw do
  get "events" => 'events#index', :as => :events

  get "events/:id" => 'events#show', :as => :event

  get "timelines" => 'timelines#index', :as => :timelines

  get "timelines/:id" => 'timelines#show', :as => :timeline

  ActiveAdmin.routes(self)

  devise_for :admin_users, :class_name => "TimelineKeeper::AdminUser"

end

app/models/timeline_keeper/admin_user.rb
module TimelineKeeper
  class AdminUser < ActiveRecord::Base
    # Include default devise modules. Others available are:
    # :token_authenticatable, :confirmable,
    # :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, 
           :recoverable, :rememberable, :trackable, :validatable
  
    # Setup accessible (or protected) attributes for your model
    attr_accessible :email, :password, :password_confirmation, :remember_me
    # attr_accessible :title, :body
  end
end

app/models/timeline_keeper/event.rb
module TimelineKeeper
  class Event < ActiveRecord::Base
    attr_accessible :caption, :credit, :end_at, :headline, 
      :media, :media_filename, :start_at, :text, :thumbnail, :timeline_ids

    has_many :timeline_events
    has_many :timelines, :through => :timeline_events

    validates :start_at, :headline, :presence => true

    # ElasticSearch setup
    include Tire::Model::Search
    include Tire::Model::Callbacks

    mapping do
      indexes :id, :index => :not_analyzed    
      indexes :media_filename, :index => :not_analyzed
      indexes :headline, :analyzer => 'snowball', :boost => 100
      indexes :text, :analyzer => 'snowball'
      indexes :start_at, :type => 'date'
    end

    settings :index => {
      :analysis => {
        :analyzer => {
          :default => {
            :type => 'snowball'
          }
        }
      }
    }

    def self.search(params)
      tire.search(:load => true) do
        query { string params } 
        sort  { by :start_at, 'asc' }     
      end
    end
    # END ElasticSearch setup

    def start_date
      start_at.strftime("%Y-%m-%d")
      # short_date(:start_at)
    end

    def end_date
      end_at ? end_at.strftime("%Y-%m-%d") : nil
      # short_date(:end_at)
    end

    def short_date(method)

      date = send(method)
      return nil if date.blank?
      parts = date.to_date.to_s.split('-')
      data = parts[0]
      if parts[1] != '01' or (parts[1] == '01' && parts[2] != '01')
        data << "-#{parts[1]}"
        if parts[2] != '01'
          data << "-#{parts[2]}"
        end
      end
      data
    end

  end
end

app/models/timeline_keeper/timeline.rb
module TimelineKeeper
  class Timeline < ActiveRecord::Base
    attr_accessible :caption, :credit, :headline, :media, :start_at, :text

    has_many :timeline_events
    has_many :events, :through => :timeline_events

    def to_label
      headline
    end
  end
end

app/models/timeline_keeper/timeline_event.rb
module TimelineKeeper
  class TimelineEvent < ActiveRecord::Base
    belongs_to :timeline
    belongs_to :event
    # attr_accessible :title, :body
  end
end

app/controllers/timeline_keeper/application_controller.rb
module TimelineKeeper
  class ApplicationController < ActionController::Base
  end
end

app/controllers/timeline_keeper/events_controller.rb
require_dependency "timeline_keeper/application_controller"

module TimelineKeeper
  class EventsController < ApplicationController
    def index
      if params[:query].present?
        @events = Event.search(params[:query])
      else
        @events = Event.limit(5).all
      end
    end
  
    def show
      @event = Event.find(params[:id])
    end
  end
end

app/controllers/timeline_keeper/timelines_controller.rb
require_dependency "timeline_keeper/application_controller"

module TimelineKeeper
  class TimelinesController < ApplicationController
    def index
      @timelines = Timeline.all
    end
  
    def show
      @timeline = Timeline.find(params[:id])
      @events   = @timeline.events.where('media IS NOT NULL OR text IS NOT NULL')
      @events_all = @timeline.events.order(:start_at)
      respond_to do |format|
        format.html
        format.json do
          # FIXME: this is terribly ugly but work so far
          dates = @events.map do |event| 
            return_event = event.attributes
            return_event[:asset] = {:media => event.media, :credit => event.credit, :caption => event.caption}
            return_event['startDate'] = return_event['start_at'].to_s.gsub('-',',')
            return_event['endDate'] = return_event['end_at'].to_s.gsub('-',',')
            return_event
          end
          timeline = @timeline.attributes
          # timeline[:asset] ={:media => @timeline.media, :credit => @timeline.credit, :caption => @timeline.caption}
          timeline[:type] = 'default'
          timeline[:date] = dates
          hash = {:timeline => timeline}
          render :json => hash.to_json
        end
      end
    end
  end
end

app/helpers/timeline_keeper/application_helper.rb
module TimelineKeeper
  module ApplicationHelper
    include ::TimelineKeeperHelper
    def external_media_url(event)
      url_for_external_media(event)
    end
  end
end

app/helpers/timeline_keeper/event_helper.rb
module TimelineKeeper
  module EventHelper
  end
end

app/helpers/timeline_keeper/timeline_helper.rb
module TimelineKeeper
  module TimelineHelper
  end
end

app/views/layouts/timeline_keeper/_navbar.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to 'Timeline Keeper', main_app.root_path, :class => :brand %>
      <div class="nav-collapse">
        <ul class="nav">
          <li><%= link_to 'Timelines', timelines_path %></li>
          <li><a href="#about">About</a></li>
          <li><a href="#contact">Contact</a></li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

app/views/layouts/timeline_keeper/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Timelinekeeper</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <%= render '/layouts/timeline_keeper/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

  <div class="container">
    <%= yield %>
  </div>

  </body>
</html>

app/views/timeline_keeper/_other_events.html.erb
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th style="width: 11em">Date</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
    <% events.each do |event| %>
      <tr>
        <td><%= event.start_date %><br><%= event.end_date %></td>
        <td>
          <% if !event.media.blank? %>
            <%= link_to external_media_url(event), :target => '_blank' do %>
              <%= image_tag event.media, :style => 'max-width: 200px;max-height:200px;float:right' %>
            <% end -%>
          <% end -%>
          <b><%= event.headline %></b><br><%= event.text %><br>
        </td>
      </tr>
    <% end -%>
  </tbody>
</table>

app/views/timeline_keeper/_search_form.html.erb
<%= form_tag events_path, :method => :get do %> 
  <p>
    <%= text_field_tag :query, params[:query] %>
    <%= submit_tag "Search Events", :name => nil %>
    <%= link_to 'clear search', events_path if defined?(@events) %>
  </p>
<% end %>

app/views/timeline_keeper/events/index.html.erb
<%= render '/timeline_keeper/search_form' %>

<%= render :partial => '/timeline_keeper/other_events', :locals => {:events => @events} %>

app/views/timeline_keeper/events/show.html.erb
<%= @event.headline %>

app/views/timeline_keeper/timelines/index.html.erb
<h1>Timelines</h1>

<%= render '/timeline_keeper/search_form' %>

<ul class="thumbnails">
  <% @timelines.each do |timeline| %>
    <li class="span3">
      <%= link_to(timeline, :class => :thumbnail) do %>
        <% if timeline.media.blank? %>
          <% if !timeline.events.where('media IS NOT NULL').limit(1).first.blank? %>
            <%= image_tag timeline.events.where('media IS NOT NULL').limit(1).first.media %>
          <% end -%>
        <% else -%>
          <%= image_tag timeline.media %>
        <% end -%>
        <h5><%= timeline.headline %></h5>
        <p><%= timeline.caption %></p>
      <% end -%>
    </li>
  <% end -%>
</ul>

app/views/timeline_keeper/timelines/show.html.erb
<h1><%= @timeline.headline %></h1>

<% if !@events.blank? %>

<div class="row" style="width:100%;height:500px">
  <div id="timeline-embed"></div>
</div>
    <script type="text/javascript">

        var timeline_config = {
            width:          "100%",
            height:         "100%",
            source:         '<%= timeline_path(@timeline, :format => :json) %>',
            start_at_end:   false,                          //OPTIONAL START AT LATEST DATE
            hash_bookmark:  true,                           //OPTIONAL LOCATION BAR HASHES
            font:           'PT',             //OPTIONAL FONT
            //lang:           'en',                           //OPTIONAL LANGUAGE
            maptype:        'watercolor',                   //OPTIONAL MAP STYLE
            css:            '<%= asset_path "verite_timeline/timeline.css" %>',     //OPTIONAL PATH TO CSS
            js:             '<%= asset_path "verite_timeline/timeline-min.js" %>'    //OPTIONAL PATH TO JS
        }
    </script>
    
<%= javascript_include_tag 'verite_timeline/timeline-embed' %>

<% end -%>

<h2>All events on this timeline</h2>
<%= render :partial => '/timeline_keeper/other_events', :locals => {:events => @events_all} %>